# TCP forwarding example
# https://gofrp.org/en/docs/examples/ssh/
serverAddr = ""
serverPort = 7000
dnsServer = "114.114.114.114"
loginFailExit = false

[log]
level = "debug"
disablePrintColor = true

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000
