# TCP forwarding example - custom TLS encryption
# https://gofrp.org/en/docs/features/common/network/network-tls/
serverAddr = ""
serverPort = 7000
dnsServer = "114.114.114.114"
loginFailExit = false

# Client certificate
transport.tls.certFile = "/sdcard/client.crt"
transport.tls.keyFile = "/sdcard/client.key"
transport.tls.trustedCaFile = "/sdcard/ca.crt"

[log]
level = "debug"
disablePrintColor = true

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000
